version: '3'
services:
  postgres:
    image: postgres:16
    container_name: term-postgres
    environment:
      POSTGRES_USER: psqluser
      POSTGRES_PASSWORD: passpsql
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
